/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: game.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "game.pb-c.h"
void   ads__request__init
                     (ADS__Request         *message)
{
  static const ADS__Request init_value = ADS__REQUEST__INIT;
  *message = init_value;
}
size_t ads__request__get_packed_size
                     (const ADS__Request *message)
{
  assert(message->base.descriptor == &ads__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__request__pack
                     (const ADS__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__request__pack_to_buffer
                     (const ADS__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__Request *
       ads__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__Request *)
     protobuf_c_message_unpack (&ads__request__descriptor,
                                allocator, len, data);
}
void   ads__request__free_unpacked
                     (ADS__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ads__response__init
                     (ADS__Response         *message)
{
  static const ADS__Response init_value = ADS__RESPONSE__INIT;
  *message = init_value;
}
size_t ads__response__get_packed_size
                     (const ADS__Response *message)
{
  assert(message->base.descriptor == &ads__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__response__pack
                     (const ADS__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__response__pack_to_buffer
                     (const ADS__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__Response *
       ads__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__Response *)
     protobuf_c_message_unpack (&ads__response__descriptor,
                                allocator, len, data);
}
void   ads__response__free_unpacked
                     (ADS__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ads__player__init
                     (ADS__Player         *message)
{
  static const ADS__Player init_value = ADS__PLAYER__INIT;
  *message = init_value;
}
size_t ads__player__get_packed_size
                     (const ADS__Player *message)
{
  assert(message->base.descriptor == &ads__player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__player__pack
                     (const ADS__Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__player__pack_to_buffer
                     (const ADS__Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__Player *
       ads__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__Player *)
     protobuf_c_message_unpack (&ads__player__descriptor,
                                allocator, len, data);
}
void   ads__player__free_unpacked
                     (ADS__Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ads__vector2__init
                     (ADS__Vector2         *message)
{
  static const ADS__Vector2 init_value = ADS__VECTOR2__INIT;
  *message = init_value;
}
size_t ads__vector2__get_packed_size
                     (const ADS__Vector2 *message)
{
  assert(message->base.descriptor == &ads__vector2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__vector2__pack
                     (const ADS__Vector2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__vector2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__vector2__pack_to_buffer
                     (const ADS__Vector2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__vector2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__Vector2 *
       ads__vector2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__Vector2 *)
     protobuf_c_message_unpack (&ads__vector2__descriptor,
                                allocator, len, data);
}
void   ads__vector2__free_unpacked
                     (ADS__Vector2 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__vector2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ads__position__init
                     (ADS__Position         *message)
{
  static const ADS__Position init_value = ADS__POSITION__INIT;
  *message = init_value;
}
size_t ads__position__get_packed_size
                     (const ADS__Position *message)
{
  assert(message->base.descriptor == &ads__position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__position__pack
                     (const ADS__Position *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__position__pack_to_buffer
                     (const ADS__Position *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__Position *
       ads__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__Position *)
     protobuf_c_message_unpack (&ads__position__descriptor,
                                allocator, len, data);
}
void   ads__position__free_unpacked
                     (ADS__Position *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ads__rotation__init
                     (ADS__Rotation         *message)
{
  static const ADS__Rotation init_value = ADS__ROTATION__INIT;
  *message = init_value;
}
size_t ads__rotation__get_packed_size
                     (const ADS__Rotation *message)
{
  assert(message->base.descriptor == &ads__rotation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__rotation__pack
                     (const ADS__Rotation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__rotation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__rotation__pack_to_buffer
                     (const ADS__Rotation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__rotation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__Rotation *
       ads__rotation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__Rotation *)
     protobuf_c_message_unpack (&ads__rotation__descriptor,
                                allocator, len, data);
}
void   ads__rotation__free_unpacked
                     (ADS__Rotation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__rotation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ads__device_info__init
                     (ADS__DeviceInfo         *message)
{
  static const ADS__DeviceInfo init_value = ADS__DEVICE_INFO__INIT;
  *message = init_value;
}
size_t ads__device_info__get_packed_size
                     (const ADS__DeviceInfo *message)
{
  assert(message->base.descriptor == &ads__device_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__device_info__pack
                     (const ADS__DeviceInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__device_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__device_info__pack_to_buffer
                     (const ADS__DeviceInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__device_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__DeviceInfo *
       ads__device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__DeviceInfo *)
     protobuf_c_message_unpack (&ads__device_info__descriptor,
                                allocator, len, data);
}
void   ads__device_info__free_unpacked
                     (ADS__DeviceInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__device_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ads__game_object__init
                     (ADS__GameObject         *message)
{
  static const ADS__GameObject init_value = ADS__GAME_OBJECT__INIT;
  *message = init_value;
}
size_t ads__game_object__get_packed_size
                     (const ADS__GameObject *message)
{
  assert(message->base.descriptor == &ads__game_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ads__game_object__pack
                     (const ADS__GameObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ads__game_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ads__game_object__pack_to_buffer
                     (const ADS__GameObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ads__game_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ADS__GameObject *
       ads__game_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ADS__GameObject *)
     protobuf_c_message_unpack (&ads__game_object__descriptor,
                                allocator, len, data);
}
void   ads__game_object__free_unpacked
                     (ADS__GameObject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ads__game_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue ads__request__type__enum_values_by_number[8] =
{
  { "SYN", "ADS__REQUEST__TYPE__SYN", 0 },
  { "INPUT", "ADS__REQUEST__TYPE__INPUT", 1 },
  { "FIN", "ADS__REQUEST__TYPE__FIN", 2 },
  { "HEARTBEAT", "ADS__REQUEST__TYPE__HEARTBEAT", 3 },
  { "DATA", "ADS__REQUEST__TYPE__DATA", 4 },
  { "LEAVE", "ADS__REQUEST__TYPE__LEAVE", 5 },
  { "DISCRETE", "ADS__REQUEST__TYPE__DISCRETE", 6 },
  { "CONTINUE", "ADS__REQUEST__TYPE__CONTINUE", 7 },
};
static const ProtobufCIntRange ads__request__type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex ads__request__type__enum_values_by_name[8] =
{
  { "CONTINUE", 7 },
  { "DATA", 4 },
  { "DISCRETE", 6 },
  { "FIN", 2 },
  { "HEARTBEAT", 3 },
  { "INPUT", 1 },
  { "LEAVE", 5 },
  { "SYN", 0 },
};
const ProtobufCEnumDescriptor ads__request__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ADS.Request.Type",
  "Type",
  "ADS__Request__Type",
  "ADS",
  8,
  ads__request__type__enum_values_by_number,
  8,
  ads__request__type__enum_values_by_name,
  1,
  ads__request__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ads__request__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ADS__Request, type),
    &ads__request__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Request, player),
    &ads__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lobby_name",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ADS__Request, lobby_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ADS__Request, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__request__field_indices_by_name[] = {
  2,   /* field[2] = lobby_name */
  3,   /* field[3] = message */
  1,   /* field[1] = player */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ads__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ads__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.Request",
  "Request",
  "ADS__Request",
  "ADS",
  sizeof(ADS__Request),
  4,
  ads__request__field_descriptors,
  ads__request__field_indices_by_name,
  1,  ads__request__number_ranges,
  (ProtobufCMessageInit) ads__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ads__response__type__enum_values_by_number[8] =
{
  { "UNKNOWN", "ADS__RESPONSE__TYPE__UNKNOWN", 0 },
  { "SYN", "ADS__RESPONSE__TYPE__SYN", 1 },
  { "INPUT", "ADS__RESPONSE__TYPE__INPUT", 2 },
  { "FIN", "ADS__RESPONSE__TYPE__FIN", 3 },
  { "HEARTBEAT", "ADS__RESPONSE__TYPE__HEARTBEAT", 4 },
  { "DATA", "ADS__RESPONSE__TYPE__DATA", 5 },
  { "LOBBY", "ADS__RESPONSE__TYPE__LOBBY", 6 },
  { "TEST", "ADS__RESPONSE__TYPE__TEST", 7 },
};
static const ProtobufCIntRange ads__response__type__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex ads__response__type__enum_values_by_name[8] =
{
  { "DATA", 5 },
  { "FIN", 3 },
  { "HEARTBEAT", 4 },
  { "INPUT", 2 },
  { "LOBBY", 6 },
  { "SYN", 1 },
  { "TEST", 7 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor ads__response__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ADS.Response.Type",
  "Type",
  "ADS__Response__Type",
  "ADS",
  8,
  ads__response__type__enum_values_by_number,
  8,
  ads__response__type__enum_values_by_name,
  1,
  ads__response__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ads__response__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ADS__Response, type),
    &ads__response__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ADS__Response, session_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sphere",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Response, sphere),
    &ads__game_object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plane",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Response, plane),
    &ads__game_object__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ADS__Response, n_players),
    offsetof(ADS__Response, players),
    &ads__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__response__field_indices_by_name[] = {
  3,   /* field[3] = plane */
  4,   /* field[4] = players */
  1,   /* field[1] = session_name */
  2,   /* field[2] = sphere */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ads__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ads__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.Response",
  "Response",
  "ADS__Response",
  "ADS",
  sizeof(ADS__Response),
  5,
  ads__response__field_descriptors,
  ads__response__field_indices_by_name,
  1,  ads__response__number_ranges,
  (ProtobufCMessageInit) ads__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ads__player__field_descriptors[8] =
{
  {
    "player_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, player_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "headset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, headset),
    &ads__device_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left_controller",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, left_controller),
    &ads__device_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right_controller",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, right_controller),
    &ads__device_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left_joystick",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, left_joystick),
    &ads__vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right_joystick",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, right_joystick),
    &ads__vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_offset",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, player_offset),
    &ads__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_ping_start",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ADS__Player, player_ping_start),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__player__field_indices_by_name[] = {
  1,   /* field[1] = headset */
  2,   /* field[2] = left_controller */
  4,   /* field[4] = left_joystick */
  0,   /* field[0] = player_name */
  6,   /* field[6] = player_offset */
  7,   /* field[7] = player_ping_start */
  3,   /* field[3] = right_controller */
  5,   /* field[5] = right_joystick */
};
static const ProtobufCIntRange ads__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ads__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.Player",
  "Player",
  "ADS__Player",
  "ADS",
  sizeof(ADS__Player),
  8,
  ads__player__field_descriptors,
  ads__player__field_indices_by_name,
  1,  ads__player__number_ranges,
  (ProtobufCMessageInit) ads__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ads__vector2__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Vector2, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Vector2, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__vector2__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange ads__vector2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ads__vector2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.Vector2",
  "Vector2",
  "ADS__Vector2",
  "ADS",
  sizeof(ADS__Vector2),
  2,
  ads__vector2__field_descriptors,
  ads__vector2__field_indices_by_name,
  1,  ads__vector2__number_ranges,
  (ProtobufCMessageInit) ads__vector2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ads__position__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Position, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Position, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Position, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__position__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange ads__position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ads__position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.Position",
  "Position",
  "ADS__Position",
  "ADS",
  sizeof(ADS__Position),
  3,
  ads__position__field_descriptors,
  ads__position__field_indices_by_name,
  1,  ads__position__number_ranges,
  (ProtobufCMessageInit) ads__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ads__rotation__field_descriptors[4] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Rotation, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Rotation, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Rotation, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(ADS__Rotation, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__rotation__field_indices_by_name[] = {
  3,   /* field[3] = w */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange ads__rotation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ads__rotation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.Rotation",
  "Rotation",
  "ADS__Rotation",
  "ADS",
  sizeof(ADS__Rotation),
  4,
  ads__rotation__field_descriptors,
  ads__rotation__field_indices_by_name,
  1,  ads__rotation__number_ranges,
  (ProtobufCMessageInit) ads__rotation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ads__device_info__field_descriptors[2] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__DeviceInfo, position),
    &ads__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__DeviceInfo, rotation),
    &ads__rotation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__device_info__field_indices_by_name[] = {
  0,   /* field[0] = position */
  1,   /* field[1] = rotation */
};
static const ProtobufCIntRange ads__device_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ads__device_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.DeviceInfo",
  "DeviceInfo",
  "ADS__DeviceInfo",
  "ADS",
  sizeof(ADS__DeviceInfo),
  2,
  ads__device_info__field_descriptors,
  ads__device_info__field_indices_by_name,
  1,  ads__device_info__number_ranges,
  (ProtobufCMessageInit) ads__device_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ads__game_object__field_descriptors[2] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__GameObject, position),
    &ads__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ADS__GameObject, rotation),
    &ads__rotation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ads__game_object__field_indices_by_name[] = {
  0,   /* field[0] = position */
  1,   /* field[1] = rotation */
};
static const ProtobufCIntRange ads__game_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ads__game_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ADS.GameObject",
  "GameObject",
  "ADS__GameObject",
  "ADS",
  sizeof(ADS__GameObject),
  2,
  ads__game_object__field_descriptors,
  ads__game_object__field_indices_by_name,
  1,  ads__game_object__number_ranges,
  (ProtobufCMessageInit) ads__game_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
