/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: game.proto */

#ifndef PROTOBUF_C_game_2eproto__INCLUDED
#define PROTOBUF_C_game_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct ADS__Request ADS__Request;
typedef struct ADS__Response ADS__Response;
typedef struct ADS__Player ADS__Player;
typedef struct ADS__Vector2 ADS__Vector2;
typedef struct ADS__Position ADS__Position;
typedef struct ADS__Rotation ADS__Rotation;
typedef struct ADS__DeviceInfo ADS__DeviceInfo;
typedef struct ADS__GameObject ADS__GameObject;


/* --- enums --- */

typedef enum _ADS__Request__Type {
  ADS__REQUEST__TYPE__SYN = 0,
  ADS__REQUEST__TYPE__INPUT = 1,
  ADS__REQUEST__TYPE__FIN = 2,
  ADS__REQUEST__TYPE__HEARTBEAT = 3,
  ADS__REQUEST__TYPE__DATA = 4,
  ADS__REQUEST__TYPE__LEAVE = 5,
  ADS__REQUEST__TYPE__DISCRETE = 6,
  ADS__REQUEST__TYPE__CONTINUE = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ADS__REQUEST__TYPE)
} ADS__Request__Type;
typedef enum _ADS__Response__Type {
  ADS__RESPONSE__TYPE__UNKNOWN = 0,
  ADS__RESPONSE__TYPE__SYN = 1,
  ADS__RESPONSE__TYPE__INPUT = 2,
  ADS__RESPONSE__TYPE__FIN = 3,
  ADS__RESPONSE__TYPE__HEARTBEAT = 4,
  ADS__RESPONSE__TYPE__DATA = 5,
  ADS__RESPONSE__TYPE__LOBBY = 6,
  ADS__RESPONSE__TYPE__TEST = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ADS__RESPONSE__TYPE)
} ADS__Response__Type;

/* --- messages --- */

struct  ADS__Request
{
  ProtobufCMessage base;
  ADS__Request__Type type;
  ADS__Player *player;
  char *lobby_name;
  char *message;
};
#define ADS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__request__descriptor) \
    , ADS__REQUEST__TYPE__SYN, NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * our lobby/session data
 */
struct  ADS__Response
{
  ProtobufCMessage base;
  ADS__Response__Type type;
  char *session_name;
  ADS__GameObject *sphere;
  ADS__GameObject *plane;
  size_t n_players;
  ADS__Player **players;
};
#define ADS__RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__response__descriptor) \
    , ADS__RESPONSE__TYPE__UNKNOWN, (char *)protobuf_c_empty_string, NULL, NULL, 0,NULL }


/*
 * our player data
 */
struct  ADS__Player
{
  ProtobufCMessage base;
  char *player_name;
  ADS__DeviceInfo *headset;
  ADS__DeviceInfo *left_controller;
  ADS__DeviceInfo *right_controller;
  ADS__Vector2 *left_joystick;
  ADS__Vector2 *right_joystick;
  ADS__Position *player_offset;
  /*
   * google.protobuf.Timestamp timestamp = 7;
   */
  char *player_ping_start;
};
#define ADS__PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__player__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, NULL, NULL, NULL, NULL, NULL, (char *)protobuf_c_empty_string }


struct  ADS__Vector2
{
  ProtobufCMessage base;
  float x;
  float y;
};
#define ADS__VECTOR2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__vector2__descriptor) \
    , 0, 0 }


struct  ADS__Position
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
};
#define ADS__POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__position__descriptor) \
    , 0, 0, 0 }


struct  ADS__Rotation
{
  ProtobufCMessage base;
  float x;
  float y;
  float z;
  float w;
};
#define ADS__ROTATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__rotation__descriptor) \
    , 0, 0, 0, 0 }


struct  ADS__DeviceInfo
{
  ProtobufCMessage base;
  ADS__Position *position;
  ADS__Rotation *rotation;
};
#define ADS__DEVICE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__device_info__descriptor) \
    , NULL, NULL }


struct  ADS__GameObject
{
  ProtobufCMessage base;
  ADS__Position *position;
  ADS__Rotation *rotation;
};
#define ADS__GAME_OBJECT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ads__game_object__descriptor) \
    , NULL, NULL }


/* ADS__Request methods */
void   ads__request__init
                     (ADS__Request         *message);
size_t ads__request__get_packed_size
                     (const ADS__Request   *message);
size_t ads__request__pack
                     (const ADS__Request   *message,
                      uint8_t             *out);
size_t ads__request__pack_to_buffer
                     (const ADS__Request   *message,
                      ProtobufCBuffer     *buffer);
ADS__Request *
       ads__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__request__free_unpacked
                     (ADS__Request *message,
                      ProtobufCAllocator *allocator);
/* ADS__Response methods */
void   ads__response__init
                     (ADS__Response         *message);
size_t ads__response__get_packed_size
                     (const ADS__Response   *message);
size_t ads__response__pack
                     (const ADS__Response   *message,
                      uint8_t             *out);
size_t ads__response__pack_to_buffer
                     (const ADS__Response   *message,
                      ProtobufCBuffer     *buffer);
ADS__Response *
       ads__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__response__free_unpacked
                     (ADS__Response *message,
                      ProtobufCAllocator *allocator);
/* ADS__Player methods */
void   ads__player__init
                     (ADS__Player         *message);
size_t ads__player__get_packed_size
                     (const ADS__Player   *message);
size_t ads__player__pack
                     (const ADS__Player   *message,
                      uint8_t             *out);
size_t ads__player__pack_to_buffer
                     (const ADS__Player   *message,
                      ProtobufCBuffer     *buffer);
ADS__Player *
       ads__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__player__free_unpacked
                     (ADS__Player *message,
                      ProtobufCAllocator *allocator);
/* ADS__Vector2 methods */
void   ads__vector2__init
                     (ADS__Vector2         *message);
size_t ads__vector2__get_packed_size
                     (const ADS__Vector2   *message);
size_t ads__vector2__pack
                     (const ADS__Vector2   *message,
                      uint8_t             *out);
size_t ads__vector2__pack_to_buffer
                     (const ADS__Vector2   *message,
                      ProtobufCBuffer     *buffer);
ADS__Vector2 *
       ads__vector2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__vector2__free_unpacked
                     (ADS__Vector2 *message,
                      ProtobufCAllocator *allocator);
/* ADS__Position methods */
void   ads__position__init
                     (ADS__Position         *message);
size_t ads__position__get_packed_size
                     (const ADS__Position   *message);
size_t ads__position__pack
                     (const ADS__Position   *message,
                      uint8_t             *out);
size_t ads__position__pack_to_buffer
                     (const ADS__Position   *message,
                      ProtobufCBuffer     *buffer);
ADS__Position *
       ads__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__position__free_unpacked
                     (ADS__Position *message,
                      ProtobufCAllocator *allocator);
/* ADS__Rotation methods */
void   ads__rotation__init
                     (ADS__Rotation         *message);
size_t ads__rotation__get_packed_size
                     (const ADS__Rotation   *message);
size_t ads__rotation__pack
                     (const ADS__Rotation   *message,
                      uint8_t             *out);
size_t ads__rotation__pack_to_buffer
                     (const ADS__Rotation   *message,
                      ProtobufCBuffer     *buffer);
ADS__Rotation *
       ads__rotation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__rotation__free_unpacked
                     (ADS__Rotation *message,
                      ProtobufCAllocator *allocator);
/* ADS__DeviceInfo methods */
void   ads__device_info__init
                     (ADS__DeviceInfo         *message);
size_t ads__device_info__get_packed_size
                     (const ADS__DeviceInfo   *message);
size_t ads__device_info__pack
                     (const ADS__DeviceInfo   *message,
                      uint8_t             *out);
size_t ads__device_info__pack_to_buffer
                     (const ADS__DeviceInfo   *message,
                      ProtobufCBuffer     *buffer);
ADS__DeviceInfo *
       ads__device_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__device_info__free_unpacked
                     (ADS__DeviceInfo *message,
                      ProtobufCAllocator *allocator);
/* ADS__GameObject methods */
void   ads__game_object__init
                     (ADS__GameObject         *message);
size_t ads__game_object__get_packed_size
                     (const ADS__GameObject   *message);
size_t ads__game_object__pack
                     (const ADS__GameObject   *message,
                      uint8_t             *out);
size_t ads__game_object__pack_to_buffer
                     (const ADS__GameObject   *message,
                      ProtobufCBuffer     *buffer);
ADS__GameObject *
       ads__game_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ads__game_object__free_unpacked
                     (ADS__GameObject *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ADS__Request_Closure)
                 (const ADS__Request *message,
                  void *closure_data);
typedef void (*ADS__Response_Closure)
                 (const ADS__Response *message,
                  void *closure_data);
typedef void (*ADS__Player_Closure)
                 (const ADS__Player *message,
                  void *closure_data);
typedef void (*ADS__Vector2_Closure)
                 (const ADS__Vector2 *message,
                  void *closure_data);
typedef void (*ADS__Position_Closure)
                 (const ADS__Position *message,
                  void *closure_data);
typedef void (*ADS__Rotation_Closure)
                 (const ADS__Rotation *message,
                  void *closure_data);
typedef void (*ADS__DeviceInfo_Closure)
                 (const ADS__DeviceInfo *message,
                  void *closure_data);
typedef void (*ADS__GameObject_Closure)
                 (const ADS__GameObject *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ads__request__descriptor;
extern const ProtobufCEnumDescriptor    ads__request__type__descriptor;
extern const ProtobufCMessageDescriptor ads__response__descriptor;
extern const ProtobufCEnumDescriptor    ads__response__type__descriptor;
extern const ProtobufCMessageDescriptor ads__player__descriptor;
extern const ProtobufCMessageDescriptor ads__vector2__descriptor;
extern const ProtobufCMessageDescriptor ads__position__descriptor;
extern const ProtobufCMessageDescriptor ads__rotation__descriptor;
extern const ProtobufCMessageDescriptor ads__device_info__descriptor;
extern const ProtobufCMessageDescriptor ads__game_object__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_game_2eproto__INCLUDED */
